CC = gcc
CFLAGS = -Wall -std=c99

all: Q11 Q12 Q2

Q11: Q11.c
	$(CC) $(CFLAGS) Q11.c -o Q11

Q12: Q12.c
	$(CC) $(CFLAGS) Q12.c -o Q12

Q2: Q2.c
	$(CC) $(CFLAGS) Q2.c -o Q2

clean:
	rm -f Q11 Q12 Q2 